# Site settings
title: Jersey
description: >
  An island of rediscovery, packed with activities to experience and explore. Begin your escape here.
baseurl: "/jersey" # the subpath of your site, e.g. /blog/
url: "https://www.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, README.md]
