# Site settings
title: Jersey
client:
  name: Jersey
  link: "https://www.jersey.com/"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Do away with the filters and discover the raw beauty of an autumnal escape in Jersey. Forage for wild foods, gaze at the stars after sunset, discover secluded beaches you’ll have all to yourself… Live life unfiltered in Jersey this autumn.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/jersey" # the subpath of your site, e.g. /blog/
img:     "/jersey/_assets/img"
css:     "/jersey/_assets/css"
js:      "/jersey/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed